### ISSUE TITLE
Report downloads (5 & 7 day) are not working for two partners

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1842] opened 2024-08-14 13:57 UTC
Washington State and Counselor Affairs reported report download issues.

**Comment by terrazoon** [comment] 2024-08-28 17:19
As of 8/28/2024, these seem to be resolved.  7 day reports can be downloaded for both services.  A number of performance improvements were implemented, with more to follow.  Closing until the issue is reported again.

**Closed by terrazoon** 2024-08-28 17:19 UTC
Labels: bug
