### ISSUE TITLE
Add conditional logic for new-user invitations to give more Login.gov information than an existing user

### ISSUE THREAD

**Issue by VRagulina** [GSA/notifications-admin#1474] opened 2024-04-24 13:50 UTC

**Comment by ccostino** [comment] 2024-05-01 16:15
@jonathanbobel, @heyitsmebev, and @em-herrick, is this issue a duplicate of https://github.com/GSA/notifications-admin/issues/1270, or something different?

I see this issue is in review, have we already addressed it elsewhere and we just need to confirm it's now live in staging and ready?

**Comment by jonathanbobel** [comment] 2024-05-01 17:59
@ccostino not sure what would have addressed this issue. #1270 didn't have conditional logic per se, but it did provide more context to signing in with login.gov

**Comment by ccostino** [comment] 2024-05-01 18:25
Okay, I think it's safe that we can close this one as a duplicate of #1270 and stay focused on seeing that one to completion. 🙂  Thanks, @jonathanbobel!

**Closed by ccostino** 2024-05-01 18:25 UTC
